apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
    - secrets
    providers:
    - aescbc:
        keys:
        - name: key1
          secret:  Z5DxgGFZ27I957FL6yhJjSa/9FMkCFUjSHPyeyJZpE4=
    - identity: {}
