apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
spec:
  template:
    spec:
      containers:
      - name: cartservice
        env:
        - name: REDIS_ADDR
          value: "myapp-redis-cart-stage:6379"