{{- if .Values.traefik.ingressRoute.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "01-application.fullname" . }}-ingressroute
  labels:
    {{- include "01-application.metadataLabels" . | nindent 4 }}
  {{- with .Values.traefik.ingressRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    {{- range .Values.traefik.ingressRoute.entryPoints }}
    - {{ . }}
    {{- end }}
  routes:
    - match: Host(`{{ .Values.traefik.ingressRoute.host }}`)
      kind: Rule
      services:
        - name: {{ include "01-application.fullname" . }}-frontendservice
          port: 80
  tls:
    secretName: {{ .Values.traefik.ingressRoute.tlsSecretName }}
{{- end -}}