apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference to shared base
resources:
  - ../../base

# Optional: Apply name prefix/suffix
nameSuffix: -dev
namePrefix: myapp-

namespace: dev

images:
- name: adservice
  newName: mahinraza556/adservice
  newTag: latest
- name: cartservice
  newName: mahinraza556/cartservice
  newTag: latest
- name: checkoutservice
  newName: mahinraza556/checkoutservice
  newTag: latest
- name: currencyservice
  newName: mahinraza556/currencyservice
  newTag: latest
- name: emailservice
  newName: mahinraza556/emailservice
  newTag: latest
- name: frontend
  newName: mahinraza556/frontend
  newTag: latest
- name: loadgenerator
  newName: mahinraza556/loadgenerator
  newTag: latest
- name: paymentservice
  newName: mahinraza556/paymentservice
  newTag: latest
- name: productcatalogservice
  newName: mahinraza556/productcatalogservice
  newTag: latest
- name: recommendationservice
  newName: mahinraza556/recommendationservice
  newTag: latest
- name: shippingservice
  newName: mahinraza556/shippingservice
  newTag: latest

labels:
  - pairs:
      env: dev
    includeSelectors: true

patches:
  - path: patch-cartservice.yaml
  - path: patch-checkoutservice.yaml
  - path: patch-recommendationservice.yaml
  - path: patch-frontend.yaml

replicas:
- count: 1
  name: adservice
- count: 1
  name: cartservice
- count: 1
  name: checkoutservice
- count: 1
  name: currencyservice
- count: 1
  name: emailservice
- count: 1
  name: frontend
- count: 1
  name: loadgenerator
- count: 1
  name: paymentservice
- count: 1
  name: productcatalogservice
- count: 1
  name: recommendationservice
- count: 1
  name: shippingservice