{{- if .Values.rediscart.enabled -}}
{{- $name := "rediscart" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "01-application.fullname" . }}-{{ $name }}
  labels:
    {{- include "01-application.metadataLabels" . | nindent 4 }}
    {{- include "01-application.selectorLabels" (list . $name) | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "01-application.selectorLabels" (list . $name) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "01-application.metadataLabels" . | nindent 8 }}
        {{- include "01-application.selectorLabels" (list . $name) | nindent 8 }}
    spec:
      {{- $svc := index .Values $name }}
      {{- if not $svc.autoscaling.enabled }}
      replicas: {{ $svc.replicaCount }}
      {{- end }}
      serviceAccountName: {{ include "01-application.fullname" . }}-{{ $name }}
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: redis
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: redis:alpine
        ports:
        - containerPort: 6379
        readinessProbe:
          periodSeconds: 5
          tcpSocket:
            port: 6379
        livenessProbe:
          periodSeconds: 5
          tcpSocket:
            port: 6379
        volumeMounts:
        - mountPath: /data
          name: redis-data
        resources:
          limits:
            memory: 256Mi
            cpu: 125m
          requests:
            cpu: 70m
            memory: 200Mi
      volumes:
      - name: redis-data
        emptyDir: {}
{{- end -}}