apiVersion: v1
kind: Pod
metadata:
  name: twin-uid
  namespace: sec-ctx
spec:
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
  containers:
    - name: preproc
      image: public.ecr.aws/docker/library/busybox:stable
      command: ["sh", "-c", "sleep infinity"]
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsUser: 1000
    - name: shipper
      image: public.ecr.aws/docker/library/busybox:stable
      command: ["sh", "-c", "sleep infinity"]
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsUser: 2000
      volumeMounts:
      - name: demo
        mountPath: /app
  volumes:
  - name: demo
    emptyDir: {}