# Configured nginx reverse proxy to forward requests to the ingress-nginx controller. That is installed in kind cluster. The ingress-nginx controller is configured to forward requests to the backend service (myapp.example.com) running in the kind cluster. The reverse proxy is configured to use SSL and to trust the ingress-nginx controller's CA certificate. The reverse proxy is also configured to set the Host header to the expected hostname (myapp.example.com) when forwarding requests to the backend service.

server {
   listen 443 ssl;
   server_name 192.168.1.50;

   ssl_certificate     /etc/nginx/certs/proxy.crt;
   ssl_certificate_key /etc/nginx/certs/proxy.key;

   location / {
     
      proxy_pass https://myapp.example.com:443;
      
      proxy_ssl_server_name on;
      
      proxy_ssl_trusted_certificate /etc/nginx/certs/ingress-ca.crt;
      proxy_ssl_verify on;
      proxy_ssl_verify_depth 2;
      
      #proxy_set_header Host $host; #404 --> We are requesting on 192.168.1.50 but ingress-nginx is expecting myapp.example.com, so we need to set the Host header to the expected hostname 
      proxy_set_header Host myapp.example.com;
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Real-IP $remote_addr;
   }
}