apiVersion: v1
kind: LimitRange
metadata:
  name: pvc-limits
  namespace: dev
spec:
  limits:
    - type: PersistentVolumeClaim
      min:
        storage: "1Gi"
      max:
        storage: "10Gi"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
spec:
  resources:
    requests:
      storage: "5Gi"

