apiVersion: v1
kind: LimitRange
metadata:
  name: pod-limit
  namespace: dev
spec:
  limits:
    - type: Pod
      min:
        cpu: "200m"
        memory: "256Mi"
      max:
        cpu: "4"
        memory: "4Gi"

# type: Pod applies limits to the total resources of the entire Pod.
# The Pod LimitRange evaluates the aggregate resources of the Pod.

# Container A
# CPU request = 1
# Container B
# CPU request = 1
# Container C
# CPU request = 1

# 1 + 1 + 1 = 3 CPU