apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      containers:
        - name: frontend
          env:
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: "myapp-productcatalogservice-stage:3550"
          - name: RECOMMENDATION_SERVICE_ADDR
            value: "myapp-recommendationservice-stage:8080"
          - name: CHECKOUT_SERVICE_ADDR
            value: "myapp-checkoutservice-stage:5050"
          - name: AD_SERVICE_ADDR
            value: "myapp-adservice-stage:9555"
          - name: SHOPPING_ASSISTANT_SERVICE_ADDR
            value: "myapp-shoppingassistantservice-stage:80"
          - name: SHIPPING_SERVICE_ADDR
            value: "myapp-shippingservice-stage:50051"
          - name: PAYMENT_SERVICE_ADDR
            value: "myapp-paymentservice-stage:50051"
          - name: EMAIL_SERVICE_ADDR
            value: "myapp-emailservice-stage:5000"
          - name: CURRENCY_SERVICE_ADDR
            value: "myapp-currencyservice-stage:7000"
          - name: CART_SERVICE_ADDR
            value: "myapp-cartservice-stage:7070"