- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: PRODUCT_CATALOG_SERVICE_ADDR
    value: "myapp-productcatalogservice-dev:3550"
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: SHIPPING_SERVICE_ADDR
    value: "myapp-shippingservice-dev:50051"
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: PAYMENT_SERVICE_ADDR
    value: "myapp-paymentservice-dev:50051"
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: EMAIL_SERVICE_ADDR
    value: "myapp-emailservice-dev:5000"
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: CURRENCY_SERVICE_ADDR
    value: "myapp-currencyservice-dev:7000"
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: CART_SERVICE_ADDR
    value: "myapp-cartservice-dev:7070"